const eng = [
    "Designation", 
    "Employ", 
    "Imply", 
    "Frantic", 
    "Delimit", 
    "Percive", 
    "Breeding Ground", 
    "Decline", 
    "Impuity", 
    "Reveal", 
    "Durable", 
    "Deteriorate", 
    "On one hand", 
    "Breeding", 
    "Oversight", 
    "Embezzlement", 
    "Have recently done so", 
    "On the other hand", 
    "Siphoning", 
    "Uphold", 
    "Sufficient", 
    "Timely", 
    "Rigorous", 
    "Withholding", 
    "Mandatory", 
    "Register", 
    "Scrutiny", 
    "Clampdown", 
    "Secrecy", 
    "Complicit", 
    "Illicit", 
    "Confiscate", 
    "Despite", 
    "On the flip side", 
    "The rest", 
    "Underlying", 
    "Exert", 
    "Sow", 
    "Divert", 
    "Common", 
    "Discontent", 
    "Coincide", 
    "Disparity", 
    "Outright", 
    "Outbreak", 
    "Misuse", 
    "Deprive", 
    "Erode", 
    "Grievance", 
    "Undermine", 
    "Deprive", 
    "Firm", 
    "Entrench", 
    "Coup", 
    "Dissent", 
    "Plight", 
    "Adept", 
    "Ignite", 
    "Casualty", 
    "Ticked me off", 
    "Ticked me off", 
    "Draw in", 
    "Moneybags", 
    "Unless", 
    "Pleasant", 
    "Bathrobe", 
    "Unravel", 
    "Catch up", 
    "Standstill", 
    "Landscape", 
    "Undue", 
    "Safeguard", 
    "Restriction", 
    "Dilute", 
    "Watchdog", 
    "Intertwine", 
    "Pervasive", 
    "Unrest", 
    "Consecutive", 
    "Lack", 
    "Decisive", 
    "Imposed", 
    "Vicious", 
    "Spark", 
    "Sparked", 
    "Impose", 
    "Dismantle"
    
];

const bhs = [
    "Penamaan (noun)", 
    "Mempekerjakan (verb)", 
    "Menyiratkan (verb)", 
    "Panik (adjective)", 
    "Membatasi (verb)", 
    "Percive (verb)", 
    "Tempat berkembang biak (noun)", 
    "Menolak (verb)", 
    "Impuitas ", 
    "Mengungkap (verb)", 
    "Tahan lama (adjective)", 
    "Memburuk (verb)", 
    "Di satu sisi ", 
    "Pembiakan (verb)", 
    "Kelalaian (noun)", 
    "Penggelapan (noun)", 
    "Baru -baru ini melakukannya", 
    "Di samping itu ", 
    "Menyedot", 
    "Menegakkan (verb)", 
    "Memadai (adjective)", 
    "Tepat waktu (adjective)", 
    "Keras (adjective)", 
    "Pemotongan", 
    "Wajib (adjective)", 
    "Daftar (verb)", 
    "Pengawasan (noun)", 
    "Penangguhan", 
    "Kerahasiaan (noun)", 
    "Terlibat (adjective)", 
    "Dilarang (noun)", 
    "Menyita (noun)", 
    "Meskipun", 
    "Di sisi lain", 
    "Sisanya", 
    "Yang mendasarinya (adjective)", 
    "Menggunakan (verb)", 
    "Menabur (verb)", 
    "Mengalihkan (verb)", 
    "Umum (adjective)", 
    "Ketidakpuasan (noun)", 
    "Bertepatan (verb)", 
    "Perbedaan (noun)", 
    "Sekaligus", 
    "Wabah (noun)", 
    "Penyalahgunaan (verb)", 
    "Mencabut (verb)", 
    "Erode (verb)", 
    "Keluhan (noun)", 
    "Merusak (verb)", 
    "Mencabut (verb)", 
    "Tegas (adjective)", 
    "Berkubu (verb)", 
    "Kup (noun)", 
    "Perbedaan pendapat (noun)", 
    "Nasib buruk (noun)", 
    "Mahir (adjective)", 
    "Menyalakan (verb)", 
    "Korban (noun)", 
    "To speak severely to and criticize someone who has done (UK Informal)", 
    "Annoy ; to annoy someone (US Informal)", 
    "Darkness & becoming dark (pharsal verb)", 
    "A rich person (noun)", 
    "Kecuali (conjuction)", 
    "Menyenangkan (adjective)", 
    "Mantel mandi (noun)", 
    "Terurai (verb)", 
    "Mengejar (noun)", 
    "Macet (noun)", 
    "Lanskap (noun", 
    "Tidak semestinya (adjective)", 
    "Menjaga (verb)", 
    "Larangan (noun)", 
    "Mencairkan (noun)", 
    "Penjaga (noun)", 
    "Berjalin (verb)", 
    "Meresap (adjective)", 
    "Kerusuhan (noun)", 
    "Berurutan (adjective)", 
    "Kekurangan (noun)", 
    "Penentu (adjective)", 
    "Dikenakan (verb)", 
    "Jahat (adjective)", 
    "Percikan (noun)", 
    "Dipicu ", 
    "Memaksakan ", 
    "Membongkar (verb)"
    
];